version: 2
# registries:
#   maven-github:
#     type: maven-repository
#     url: https://maven.pkg.github.com/octocat
#     username: octocat
#     password: ${{secrets.MY_ARTIFACTORY_PASSWORD}}
#   npm-npmjs:
#     type: npm-registry
#     url: https://registry.npmjs.org
#     username: octocat
#     password: ${{secrets.MY_NPM_PASSWORD}}
#   github-hex-org:
#     type: hex-organization
#     organization: github
#     key: ${{secrets.MY_HEX_ORGANIZATION_KEY}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "moment-timezone"  